### ISSUE TITLE
[CHANGE]: Consistent Handling of JSON Properties

### ISSUE THREAD

**Issue by haasy** [mobile-directing-system/mds-server#51]
### Desired Change

When creating a User JSON of the form 
```
{
  id: '',
  ...
}
```
is correctly parsed and the correct User is created. If instead a operation is created with the following JSON
```
{
  id:"",
  ...
}
```
then the creation of the operation fails, because the id cannot be parsed as a valid UUID.

It would be nice if the behavior between these endpoints could be consistent. Preferably the operations endpoint should have the behavior of the users endpoint with respect to passed ids. 

### Reason/Motivation for Change

Endpoints can be more intuitively used if the behavior between them is consistent.

**Comment by lefinal** [comment]
closing this because of invalid payload. documentation clearly specifies that no `id`-field should be passed. as an alternative, you can set it to `null`. the reason, why its working with creating users is, that the `id`-field is getting dropped and no 100% strict JSON parsing being involved here. there was a separation of requests and response content because of the `pass`-field. in the cases, we reuse the content-description (or structure) for all endpoints which means, that if the id field is not empty (an an empty string is _not_ empty!), it is parsed as UUID.
